import fs from 'fs';
import path from 'path';
import { execFileSync } from 'child_process';
import { generateSeo } from './generate-seo.js';

// Pre-render the programmatic SEO landing pages (state / DISCOM / directory) and refresh
// sitemap.xml + robots.txt into the source tree BEFORE copying, so the recursive copy picks
// them up and the sitemap is always current on every deploy.
generateSeo();

const dist = 'dist';

// What ships is decided by EXCLUSION, not by an inventory.
//
// This used to be a hand-written list of directories to copy. It silently fell behind the
// site: `mr/`, `ta/`, `smart-meter-recharge/`, `fppa/`, `usage/`, `install/` and a dozen more
// were never added, so 410 of 565 pages reached dist and the other 155 would have 404'd on
// any host fed from it. Nothing failed — the missing pages simply were not there.
//
// An inventory of what to include has to be updated every time a page is added, and forgetting
// is invisible. An inventory of what to leave out only changes when the toolchain changes, and
// the check at the bottom catches a mistake either way.
const EXCLUDE_DIRS = new Set([
  'node_modules', 'dist', '.build',
  'tests', 'scripts', 'docs', 'supabase',       // build-time and reference only
  'graphify-out', 'thediscombill.com-audit',
]);

// Build-time sources and repo furniture. These sit at the root next to the pages, so they
// cannot be excluded by directory.
const EXCLUDE_FILES = new Set([
  'build.js', 'generate-seo.js',
  'guides-content.js', 'glossary-content.js', 'smart-meter-content.js',
  'smart-meter-svg.js', 'understand-bill-content.js',
  'worker.js', 'wrangler.jsonc',                // Cloudflare entry point, not an asset
  'package.json', 'package-lock.json',
  'README.md', 'CONTRIBUTING.md', 'TARIFF_GUIDE.md',
  'sitemap-lastmod.json',                       // build bookkeeping, not served
]);

// Tooling output that must never ship, at ANY depth. EXCLUDE_DIRS is deliberately root-only,
// because a name like docs/ could legitimately be a page path deeper in the site. These names
// could not: they are generated by local tooling. js/graphify-out/ is what caught this out —
// gitignored, so it never reached the repo and never shipped from CI, but a local build copied
// it into dist/ and its cache index carried the author's name.
const EXCLUDE_ANYWHERE = new Set(['node_modules', 'graphify-out']);

// GitHub Pages already ignores dot- and underscore-prefixed entries, so matching that keeps
// dist equivalent to what the current host serves.
//
// The two exceptions are Cloudflare's own asset-config files. They are underscore-prefixed
// precisely so the current host ignores them, which means the blanket rule above would also
// stop them from ever reaching the deploy that needs them.
const ASSET_CONFIG = new Set(['_headers', '_redirects']);
const isHidden = name => !ASSET_CONFIG.has(name) && (name.startsWith('.') || name.startsWith('_'));

function copyTree(src, dest) {
  let files = 0;
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const name = entry.name;
    if (isHidden(name)) continue;
    const from = path.join(src, name);
    const to = path.join(dest, name);
    if (entry.isDirectory()) {
      if (EXCLUDE_ANYWHERE.has(name)) continue;
      if (src === '.' && EXCLUDE_DIRS.has(name)) continue;
      fs.mkdirSync(to, { recursive: true });
      files += copyTree(from, to);
    } else {
      if (src === '.' && EXCLUDE_FILES.has(name)) continue;
      fs.copyFileSync(from, to);
      files++;
    }
  }
  return files;
}

fs.rmSync(dist, { recursive: true, force: true });   // no stale files from a previous shape
fs.mkdirSync(dist, { recursive: true });
const copied = copyTree('.', dist);

// ── the check that makes the exclusion safe ─────────────────────────────────
// Copying by exclusion can still lose pages — a bad EXCLUDE entry, a rename, a partial write.
// Every HTML page git tracks must exist in dist, and the build fails naming the ones that do
// not. This is the part the old list never had.
const countHtml = dir => fs.readdirSync(dir, { withFileTypes: true }).reduce((n, e) =>
  n + (e.isDirectory() ? countHtml(path.join(dir, e.name)) : e.name.endsWith('.html') ? 1 : 0), 0);

// Deliberately UNFILTERED. Filtering this list by EXCLUDE_DIRS made the check self-fulfilling:
// excluding a directory also removed it from what was expected, so dropping mr/ and ta/ still
// reported "all present". Every tracked .html is a page of this site, so the expectation is
// simply all of them — and adding an EXCLUDE entry can no longer quietly lower the bar.
let tracked = [];
try {
  tracked = execFileSync('git', ['ls-files', '*.html'], { encoding: 'utf8' })
    .split('\n').filter(Boolean);
} catch {
  console.warn('  (git unavailable — skipping the page-coverage check)');
}

if (tracked.length) {
  const missing = tracked.filter(p => !fs.existsSync(path.join(dist, p)));
  if (missing.length) {
    console.error(`\nBuild failed: ${missing.length} tracked page(s) missing from ${dist}/`);
    for (const p of missing.slice(0, 20)) console.error('  ' + p);
    if (missing.length > 20) console.error(`  …and ${missing.length - 20} more`);
    process.exit(1);
  }
  console.log(`  ${tracked.length} tracked pages, all present in ${dist}/`);
}

console.log(`Build complete. ${copied} files (${countHtml(dist)} HTML) in ${dist}/.`);
