// tests/site.test.mjs — dependency-free integrity checks over the generated static site.
// Run with:  node tests/site.test.mjs
//
// The site is 445 hand-cross-linked pages generated by generate-seo.js. Two things rot
// silently there and neither the engine tests nor the eye catch them:
//   1. Internal links to pages/assets that don't exist (a renamed slug, a dropped route).
//   2. SEO pages missing the structural essentials (title, single H1, canonical).
// This walks the built tree and fails on either. Run after `npm run seo`.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const IGNORE = new Set(['node_modules', '.git', 'dist', '.wrangler', 'graphify-out', 'supabase']);

let passed = 0, failed = 0;
const fail = (msg) => { failed++; console.error(`  ✗ ${msg}`); };

// ── collect every file + the .html pages ──────────────────────────────────────
const files = new Set();     // repo-relative, forward slashes
const htmlPages = [];
(function walk(dir) {
  for (const name of fs.readdirSync(dir)) {
    if (IGNORE.has(name)) continue;
    const abs = path.join(dir, name);
    const rel = path.relative(ROOT, abs).replace(/\\/g, '/');
    if (fs.statSync(abs).isDirectory()) walk(abs);
    else { files.add(rel); if (rel.endsWith('.html')) htmlPages.push(rel); }
  }
})(ROOT);

// Resolve an internal link target to a repo-relative file; return null if unresolvable form.
function resolveTarget(href, fromFile) {
  let t = href.split('#')[0].split('?')[0];
  if (!t) return null;                                  // pure #fragment / query → same page
  if (t.startsWith('/')) t = t.slice(1);                // root-absolute
  else t = path.posix.join(path.posix.dirname(fromFile), t);  // relative to the page
  t = t.replace(/\/$/, '');                             // trim trailing slash
  return t;                                             // '' means site root
}
function targetExists(t) {
  if (t === '') return files.has('index.html');
  return files.has(t) || files.has(`${t}/index.html`) || files.has(`${t}.html`);
}

// ── 1. internal-link integrity ────────────────────────────────────────────────
console.log('\n• internal-link integrity');
const broken = new Map();   // "page → href" dedup
for (const page of htmlPages) {
  const html = fs.readFileSync(path.join(ROOT, page), 'utf8');
  const links = [...html.matchAll(/(?:href|src)="([^"]+)"/g)].map(m => m[1]);
  for (const href of links) {
    if (/^(https?:|mailto:|tel:|data:|javascript:|\/\/|#)/.test(href)) continue;   // external/inline/anchor
    const t = resolveTarget(href, page);
    if (t === null) continue;
    if (!targetExists(t)) broken.set(`${page}  →  ${href}`, true);
  }
}
if (broken.size) { for (const k of broken.keys()) fail(`broken link: ${k}`); }
else { passed++; console.log(`  ✓ all internal links resolve (${htmlPages.length} pages scanned)`); }

// ── 2. SEO-page structure (generated content pages only) ──────────────────────
console.log('\n• SEO page structure');
const SEO = /^(guides|tariffs|fppa|database|glossary|smart-meter-recharge|hi|mr|ta)\//;
let seoChecked = 0, seoBad = 0;
for (const page of htmlPages) {
  if (!SEO.test(page)) continue;
  seoChecked++;
  const html = fs.readFileSync(path.join(ROOT, page), 'utf8');
  const h1s = (html.match(/<h1[ >]/g) || []).length;
  const probs = [];
  if (!/<title>[^<]+<\/title>/.test(html)) probs.push('missing <title>');
  if (h1s !== 1) probs.push(`${h1s} <h1> (want 1)`);
  if (!/<link rel="canonical"/.test(html)) probs.push('missing canonical');
  if (probs.length) { seoBad++; fail(`${page}: ${probs.join(', ')}`); }
}
if (!seoBad) { passed++; console.log(`  ✓ title / single-H1 / canonical present (${seoChecked} SEO pages)`); }

// ── 3. /fuel-surcharge/ is in step with js/tariffs/fppa.js ────────────────────
// The tracker is pre-rendered at build time, so a new FPPA notice added to fppa.js does not
// reach the page until `npm run seo` runs again — and nothing about the site looks broken in
// the meantime. It just quietly shows last month's figure. This is the one page whose data
// changes monthly, so it is the one most likely to rot unnoticed.
//
// The check is content-derived, not mtime-based: mtimes are meaningless after a fresh clone.
// It recomputes what the current data says and asserts the page actually says it.
console.log('\n• /fuel-surcharge/ matches fppa.js');
{
  const page = path.join(ROOT, 'fuel-surcharge', 'index.html');
  if (!fs.existsSync(page)) {
    fail('fuel-surcharge/index.html missing — run `npm run seo`');
  } else {
    const html = fs.readFileSync(page, 'utf8');
    const { FPPA_BY_STATE, FPPA_BY_DISCOM, pick } =
      await import(pathToFileURL(path.join(ROOT, 'js', 'tariffs', 'fppa.js')).href);

    // Mirror generate-seo.js's fsRate() exactly — if that formatting changes, this must too.
    const rupee = (n) => '₹' + Number(n).toLocaleString('en-IN',
      { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    const fsRate = (e) => e.mode === 'percent'
      ? `${e.rate > 0 ? '+' : ''}${e.rate.toFixed(2)}%`
      : `${rupee(e.rate)}/unit`;

    const today = new Date().toISOString().slice(0, 10);
    let stale = 0;
    for (const [name, list] of [...Object.entries(FPPA_BY_STATE), ...Object.entries(FPPA_BY_DISCOM)]) {
      const cur = pick(list, today);
      if (!cur) continue;                       // nothing in force today → page shows a fallback
      if (!html.includes(fsRate(cur))) {
        stale++;
        fail(`${name}: current rate ${fsRate(cur)} is not on the page — run \`npm run seo\``);
      }
    }

    // Every UP month must have a bar. Catches a month appended to the series without a regen,
    // which the rate check alone would miss when the newest month is not yet in force.
    const bars = (html.match(/class="fs-bar fs-bar-(?:pos|neg)"/g) || []).length;
    const upMonths = FPPA_BY_STATE['Uttar Pradesh'].length;
    if (bars !== upMonths) {
      stale++;
      fail(`UP chart has ${bars} bars for ${upMonths} months — run \`npm run seo\``);
    }

    if (!stale) { passed++; console.log(`  ✓ current rates and the ${bars}-month UP chart are in step`); }
  }
}

// ── 4. footer link parity ─────────────────────────────────────────────────────
// Most pages get their footer from generate-seo.js, but a handful are hand-written and
// keep their own copy. Those copies drift: a link added to the shared footer never
// reaches them, and nothing looks broken — the column is just quietly shorter.
//
// No hardcoded list here, because that would need updating every time the footer does.
// Instead the standard is derived from the pages themselves: any link carried by the
// large majority of footers is expected in all of them. A genuinely new link is below
// the threshold until it is on most pages, so adding one does not fail the suite.
console.log('\n• footer link parity');
{
  const QUORUM = 0.9;
  const footers = new Map();   // page → Set of hrefs in its <footer>
  for (const page of htmlPages) {
    const html = fs.readFileSync(path.join(ROOT, page), 'utf8');
    const m = html.match(/<footer[\s\S]*?<\/footer>/i);
    if (!m) continue;
    // The account pages (/login/, /profile/, /my-bills/) carry a deliberately minimal
    // footer — copyright and social only, no link columns. That is a design choice, not
    // drift, so only footers that actually have the columns are held to the standard.
    if (!m[0].includes('footer-col')) continue;
    const hrefs = new Set();
    for (const a of m[0].matchAll(/<a\b[^>]*\bhref="([^"]+)"/gi)) {
      const href = a[1];
      // Root-absolute internal links only: relative paths and the social/mailto links
      // legitimately differ per page.
      if (href.startsWith('/') && !href.startsWith('//')) hrefs.add(href.split('#')[0]);
    }
    // Vernacular twins link to /hi/... equivalents, so they are a separate population
    // and would drag every English href below quorum. Compare English pages only.
    if (!/^(hi|mr|ta)\//.test(page) && hrefs.size) footers.set(page, hrefs);
  }

  const count = new Map();
  for (const hrefs of footers.values()) for (const h of hrefs) count.set(h, (count.get(h) || 0) + 1);
  const standard = [...count.entries()]
    .filter(([, n]) => n >= footers.size * QUORUM)
    .map(([h]) => h);

  let drifted = 0;
  for (const [page, hrefs] of footers) {
    const missing = standard.filter((h) => !hrefs.has(h));
    if (missing.length) { drifted++; fail(`${page}: footer missing ${missing.join(', ')}`); }
  }
  if (!drifted) {
    passed++;
    console.log(`  ✓ ${standard.length} standard links present in all ${footers.size} footers`);
  }
}

// ── 5. content.min.css is in step with styles.css and the pages it serves ─────
// The 467 generated content pages link a slim sheet built from their own markup by
// scripts/split-css.mjs. Two ways that rots silently, neither of which looks broken until
// someone loads a page: a rule is added to styles.css and the slim sheet is never rebuilt,
// or a page starts using a component whose rules were dropped. Both leave the site looking
// fine on the pages you happen to check.
//
// Content-derived like the FPPA check above, not mtime-based: it rebuilds the sheet from
// the current sources and asserts the file on disk is what that produces.
console.log('\n• content.min.css matches its sources');
{
  const slim = path.join(ROOT, 'css', 'content.min.css');
  if (!fs.existsSync(slim)) {
    fail('css/content.min.css missing — run `npm run seo`');
  } else {
    const onDisk = fs.readFileSync(slim, 'utf8');
    const { buildContentCss } = await import(pathToFileURL(path.join(ROOT, 'scripts', 'split-css.mjs')).href);

    // buildContentCss writes as a side effect, so snapshot and restore: a test must not
    // leave the tree different from how it found it.
    const rebuilt = (() => {
      const before = onDisk;
      try { buildContentCss({ quiet: true }); return fs.readFileSync(slim, 'utf8'); }
      finally { fs.writeFileSync(slim, before, 'utf8'); }
    })();

    if (rebuilt !== onDisk) {
      fail(`css/content.min.css is stale (${onDisk.length} B on disk, ${rebuilt.length} B rebuilt) — run \`npm run seo\``);
    } else {
      // Every page must be on exactly one sheet. A page on neither loses all styling; a page
      // on both downloads the slim sheet for nothing.
      let bad = 0;
      for (const page of htmlPages) {
        const html = fs.readFileSync(path.join(ROOT, page), 'utf8');
        const c = html.includes('css/content.min.css'), f = html.includes('css/styles.min.css');
        if (c && f) { bad++; fail(`${page}: links both stylesheets`); }
      }
      // A selector that names no class or id at all - `table`, `time`, `:root`, `a:hover` -
      // applies to every page by definition, so it must survive into the slim sheet. The
      // splitter used to judge a whole comma-separated LIST as one unit, so grouping such a
      // selector with a tool-only class threw the element selector away too: `table,
      // .stat-number, time { font-variant-numeric: tabular-nums }` vanished, and every rate
      // table on every tariff and guide page silently lost its tabular figures.
      const bareSelectors = new Set();
      const full = fs.readFileSync(path.join(ROOT, 'css', 'styles.css'), 'utf8')
        .replace(/\/\*[\s\S]*?\*\//g, '');
      for (const m of full.matchAll(/(^|[};])\s*([^{};@]+)\{/g)) {
        for (const part of m[2].split(',')) {
          const sel = part.trim();
          // Bare element selectors only, and only simple ones - compound and functional
          // forms bring their own matching rules that this check has no business asserting.
          if (!sel || /[.#[(]/.test(sel)) continue;
          if (!/^[a-z][a-z0-9-]*(\s*:{1,2}[a-z-]+)?$/i.test(sel)) continue;
          if (/^(from|to)$/i.test(sel)) continue;            // @keyframes stops
          bareSelectors.add(sel.replace(/\s+/g, ''));
        }
      }
      const dropped = [...bareSelectors].filter(sel => {
        const re = new RegExp(`(^|[},])${sel.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[,{]`);
        return !re.test(onDisk);
      });
      if (dropped.length) {
        fail(`content.min.css dropped class-free selectors that apply to every page:\n    `
          + dropped.slice(0, 12).join(', '));
      } else if (!bad) {
        passed++;
        const pct = Math.round(100 - (onDisk.length / fs.statSync(path.join(ROOT, 'css', 'styles.min.css')).size) * 100);
        console.log(`  ✓ rebuilt byte-for-byte; ${pct}% smaller; all ${bareSelectors.size} class-free selectors kept`);
      }
    }
  }
}

// ── 6. SERP width budget for titles and meta descriptions ────────────────────
// Google truncates by pixel width, so this measures width rather than character count:
// 1 unit = one Latin lowercase character, with uppercase (1.5) and digits (1.23) costing
// more and Devanagari (0.95) slightly less. A corpus full of "UPPCL MSEDCL TANGEDCO 2026"
// blows the title box well before 60 characters, which a .length check would wave through.
//
// The model is re-implemented here rather than imported from generate-seo.js on purpose:
// a test that calls the same function it is checking agrees with it by construction and
// proves nothing. If these two drift, that disagreement is itself the signal.
//
// TITLE_W is 72, matching TITLE_WIDTH in generate-seo.js — see the note there for why the
// title budget is the mobile two-line allowance and not the classic desktop 60. Keep the two
// in step: this constant is duplicated deliberately, not accidentally.
console.log('\n• title / description fit the SERP width budget');
{
  const TITLE_W = 72, DESC_W = 155;
  const cw = (c) => {
    const o = c.codePointAt(0);
    if (o === 32) return 0.454;
    if (o >= 0x41 && o <= 0x5a) return 1.501;
    if (o >= 0x30 && o <= 0x39) return 1.227;
    if (o >= 0x900 && o <= 0x97f) return 0.951;
    if (o >= 0xb80 && o <= 0xbff) return 1.378;
    if (o >= 0x300 && o <= 0x36f) return 0;
    return 1;
  };
  const width = (s) => [...s].reduce((a, c) => a + cw(c), 0);
  const unesc = (s) => s.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"').replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(+n))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCodePoint(parseInt(n, 16)));

  // A CTR experiment holds these seven snippets at full length until 2026-09-15; see the
  // HOLD_SNIPPET note in generate-seo.js. Once that date passes the guard there stops
  // applying and these pages must satisfy the budget like everything else.
  const HELD = new Set([
    'guides/tneb-tangedco-new-connection', 'guides/haryana-new-connection-dhbvn-uhbvn',
    'guides/bescom-new-connection-online', 'guides/kseb-new-connection-online',
    'guides/tata-power-ddl-new-connection', 'guides/uppcl-new-connection-jhatpat',
    'guides/msedcl-new-connection-online',
  ]);
  const holdActive = new Date().toISOString().slice(0, 10) < '2026-09-15';

  let over = 0, checked = 0, worstT = 0, worstD = 0;
  for (const page of htmlPages) {
    const html = fs.readFileSync(path.join(ROOT, page), 'utf8');
    // Only pages that ask to be indexed — noindex stubs never reach a SERP.
    const rob = html.match(/<meta name="robots" content="([^"]*)"/i);
    if (rob && /noindex/i.test(rob[1])) continue;
    checked++;

    const t = html.match(/<title>([^<]*)<\/title>/i);
    if (t) {
      const w = width(unesc(t[1].trim()));
      worstT = Math.max(worstT, w);
      if (w > TITLE_W + 0.01) { over++; fail(`${page}: title ${w.toFixed(1)} > ${TITLE_W} units — ${t[1].trim()}`); }
    }

    const d = html.match(/<meta name="description" content="([^"]*)"/i);
    if (d) {
      const slug = page.replace(/\/index\.html$/, '').replace(/\.html$/, '');
      if (holdActive && HELD.has(slug)) continue;
      const w = width(unesc(d[1].trim()));
      worstD = Math.max(worstD, w);
      if (w > DESC_W + 0.01) { over++; fail(`${page}: description ${w.toFixed(1)} > ${DESC_W} units`); }
    }
  }
  if (!over) {
    passed++;
    console.log(`  ✓ ${checked} indexable pages within budget (worst title ${worstT.toFixed(1)}/${TITLE_W}, description ${worstD.toFixed(1)}/${DESC_W})`);
  }
}

// ── 7. the tariff index is in step, and the homepage stays off the tariff data ──
// Two failure modes, both silent:
//   a) js/tariffs/index.js is generated from the 34 state files. Edit a state file without
//      running `npm run seo` and the index still lists the old DISCOMs — dropdowns and page
//      titles then disagree with the rates behind them.
//   b) The whole point of the split is that a visitor who has not chosen a state downloads
//      no tariff tables. A single stray `import './tariffs/<state>.js'` — or re-adding the
//      bill-ocr script tag to index.html — quietly puts all 34 back on the critical path.
console.log('\n• tariff index fresh, and off the homepage critical path');
{
  const idxPath = path.join(ROOT, 'js', 'tariffs', 'index.js');
  if (!fs.existsSync(idxPath)) {
    fail('js/tariffs/index.js missing — run `npm run seo`');
  } else {
    const onDisk = fs.readFileSync(idxPath, 'utf8');
    const { buildTariffIndex } = await import(pathToFileURL(path.join(ROOT, 'scripts', 'build-tariff-index.mjs')).href);
    // buildTariffIndex writes as a side effect; snapshot and restore so the test leaves the
    // tree exactly as it found it.
    let rebuilt;
    try { await buildTariffIndex({ quiet: true }); rebuilt = fs.readFileSync(idxPath, 'utf8'); }
    finally { fs.writeFileSync(idxPath, onDisk, 'utf8'); }

    let bad = 0;
    if (rebuilt !== onDisk) {
      bad++;
      fail(`js/tariffs/index.js is stale (${onDisk.length} B on disk, ${rebuilt.length} B rebuilt) — run \`npm run seo\``);
    }

    // Walk the static import graph from every <script type="module"> on the homepage and
    // assert no per-state tariff module is reachable without a dynamic import().
    const stateFiles = new Set(fs.readdirSync(path.join(ROOT, 'js', 'tariffs'))
      .filter((f) => f.endsWith('.js') &&
        // Keep in step with NOT_A_STATE in scripts/build-tariff-index.mjs.
        !['registry.js', 'index.js', 'fppa.js', 'fppa-resolve.js', 'subsidy.js', 'surcharge-terms.js', 'orders.js'].includes(f))
      .map((f) => `tariffs/${f}`));

    const home = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
    const entries = [...home.matchAll(/<script[^>]+type="module"[^>]+src="([^"]+)"/g)]
      .map((m) => m[1].replace(/^\.?\//, '').replace(/^js\//, ''));

    const seen = new Set();
    const reached = [];
    const walk = (rel, trail) => {
      if (seen.has(rel)) return;
      seen.add(rel);
      if (stateFiles.has(rel)) { reached.push([...trail, rel].join(' → ')); return; }
      const abs = path.join(ROOT, 'js', rel);
      if (!fs.existsSync(abs)) return;
      const src = fs.readFileSync(abs, 'utf8');
      // STATIC edges only — `import(...)` is exactly what we want people to use. The
      // alternation has to include the bare side-effect form (`import './x.js';`, no
      // `from`), which is the easiest way to pull a module in by accident.
      for (const m of src.matchAll(/(?:^|[\n;}])\s*(?:import\s[^\n]*?from|export\s[^\n]*?from|import)\s*['"](\.{1,2}\/[^'"]+)['"]/g)) {
        walk(path.posix.normalize(path.posix.join(path.posix.dirname(rel), m[1])), [...trail, rel]);
      }
    };
    for (const e of entries) walk(e, []);

    if (reached.length) {
      bad++;
      for (const chain of reached) fail(`homepage statically reaches tariff data: ${chain}`);
    }
    if (!bad) {
      passed++;
      console.log(`  ✓ index rebuilt byte-for-byte; ${entries.length} homepage module entr${entries.length === 1 ? 'y' : 'ies'} reach 0 of ${stateFiles.size} state files`);
    }
  }
}

// ── 8. tariff database is in step with tariff modules ─────────────────────────
// The tariff database is the structured asset behind the public tariff pages. It is
// generated from the same state/DISCOM modules, so a tariff edit should never leave
// the JSON snapshot stale.
console.log('\n• tariff database fresh');
{
  const dbPath = path.join(ROOT, '.build', 'tariff-database.json');
  const summaryPath = path.join(ROOT, '.build', 'tariff-database-summary.json');
  if (!fs.existsSync(dbPath) || !fs.existsSync(summaryPath)) {
    fail('tariff database files missing — run `npm run seo`');
  } else {
    const beforeDb = fs.readFileSync(dbPath, 'utf8');
    const beforeSummary = fs.readFileSync(summaryPath, 'utf8');
    const { ensureAll } = await import(pathToFileURL(path.join(ROOT, 'js', 'tariffs', 'registry.js')).href);
    const { buildTariffDatabase } = await import(pathToFileURL(path.join(ROOT, 'scripts', 'build-tariff-database.mjs')).href);
    await ensureAll();
    let rebuiltDb, rebuiltSummary;
    try {
      buildTariffDatabase({ quiet: true });
      rebuiltDb = fs.readFileSync(dbPath, 'utf8');
      rebuiltSummary = fs.readFileSync(summaryPath, 'utf8');
    } finally {
      fs.writeFileSync(dbPath, beforeDb, 'utf8');
      fs.writeFileSync(summaryPath, beforeSummary, 'utf8');
    }

    if (rebuiltDb !== beforeDb || rebuiltSummary !== beforeSummary) {
      fail('tariff database is stale — run `npm run seo`');
    } else {
      const summary = JSON.parse(beforeSummary);
      if (summary.stateCount < 30 || summary.discomCount < 60 || summary.tariffRecordCount < summary.discomCount) {
        fail(`tariff database coverage looks too small (${summary.stateCount} states, ${summary.discomCount} DISCOMs, ${summary.tariffRecordCount} tariff records)`);
      } else {
        passed++;
        console.log(`  ✓ database regenerated byte-for-byte (${summary.stateCount} states, ${summary.discomCount} DISCOMs, ${summary.tariffRecordCount} tariff records)`);
      }
    }
  }
}

// ── 9. the coverage numbers we advertise match the database ───────────────────
// The homepage, its FAQ schema, the i18n strings and llms.txt all quote how much ground the
// site covers. Those are hand-written, and they drifted: the homepage claimed "150+ consumer
// categories" against 131 in the database, "65+ DISCOMs" against exactly 65, and "35 states"
// against 34. They are the easiest claims on the site for a reader to check — /database/ prints
// the real figures one click away — so a stale number here costs more than it looks.
// Every count must appear as a bare figure, never "65+", because "+" asserts more than we have.
console.log('\n• advertised coverage matches the database');
{
  const summaryPath = path.join(ROOT, '.build', 'tariff-database-summary.json');
  if (!fs.existsSync(summaryPath)) {
    fail('tariff-database-summary.json missing — run `npm run seo`');
  } else {
    const s = JSON.parse(fs.readFileSync(summaryPath, 'utf8'));
    const problems = [];
    // js/i18n/<lang>.js was never in this list, so three languages quietly carried
    // "35+ states / 65+ DISCOMs" — inflated AND wrong — for as long as the English copy
    // has been correct. The rule only ever applied to the language nobody had to translate.
    const sources = ['index.html', 'llms.txt', path.join('js', 'i18n.js'),
      ...fs.readdirSync(path.join(ROOT, 'js', 'i18n'))
        .filter(f => f.endsWith('.js')).map(f => path.join('js', 'i18n', f))];

    for (const rel of sources) {
      const p = path.join(ROOT, rel);
      if (!fs.existsSync(p)) continue;
      const text = fs.readFileSync(p, 'utf8');

      // An inflated "N+" next to one of these nouns is the exact shape of the old bug.
      // The noun-anchored rule below cannot fire on a translated string — the noun is in
      // Devanagari or Tamil, so an inflated count there slipped through for as long as it
      // existed. Inside a string table the policy is simpler and stricter: exact counts
      // only, so any "N+" is the defect regardless of which script follows it.
      if (rel.startsWith(path.join('js', 'i18n') + path.sep)) {
        for (const m of text.matchAll(/'([^']+)':\s*'([^']*\d+\+[^']*)'/g)) {
          problems.push(`${rel}: ${m[1]} — advertise the exact count, not "N+"`);
        }
      }

      for (const m of text.matchAll(/(\d+)\+\s*(?:Indian\s+)?(DISCOM|consumer categor|categor|states?\s*&|states?\s+and|states?\b)/gi)) {
        problems.push(`${rel}: "${m[1]}+ ${m[2]}…" — advertise the exact count, not "${m[1]}+"`);
      }
      // And any bare figure attached to those nouns has to be the real one.
      const checks = [
        [/(\d+)\s+DISCOM/gi, s.discomCount, 'DISCOMs'],
        [/(\d+)\s+consumer categor/gi, s.categoryCount, 'consumer categories'],
        [/(\d+)\s+(?:Indian\s+)?states?\s*(?:&amp;|&|and)\s*(?:UT|union)/gi, s.stateCount, 'states/UTs'],
      ];
      for (const [re, expected, label] of checks) {
        for (const m of text.matchAll(re)) {
          if (Number(m[1]) !== expected) problems.push(`${rel}: claims ${m[1]} ${label}, database has ${expected}`);
        }
      }
    }

    // The tariff directory hero carried "65+ DISCOMs" in all four languages for as long as
    // it existed, and nothing here looked at it: the loop above scans index.html, llms.txt
    // and the string tables, none of which is where that row is built. A whole-file scan of
    // the directory page is not the fix either — it legitimately prints per-state counts
    // ("1 DISCOM", "4 DISCOMs") that would fail against the site total. So the check is
    // scoped to the hero row, where every figure is a site-wide total by definition, and
    // inside it any "N+" is wrong in every script: these numbers come from the database and
    // are exact. That also covers hi/mr/ta, whose nouns the noun-anchored rule cannot match.
    const dirPages = [null, 'hi', 'mr', 'ta'].map(l => l
      ? path.join(l, 'tariffs', 'states', 'index.html')
      : path.join('tariffs', 'states', 'index.html'));
    for (const rel of dirPages) {
      const p = path.join(ROOT, rel);
      if (!fs.existsSync(p)) continue;
      const row = /<div class="seo-dir-stats"[\s\S]*?<\/div>/.exec(fs.readFileSync(p, 'utf8'));
      if (!row) { problems.push(`${rel}: hero stat row not found — markup changed`); continue; }
      for (const hit of row[0].matchAll(/(\d+)\+/g)) {
        problems.push(`${rel}: hero stat "${hit[1]}+" — advertise the exact count, not "${hit[1]}+"`);
      }
      const nums = [...row[0].matchAll(/<strong>(\d+)\+?<\/strong>/g)].map(x => Number(x[1]));
      if (nums[0] !== undefined && nums[0] !== s.stateCount) {
        problems.push(`${rel}: hero claims ${nums[0]} states, database has ${s.stateCount}`);
      }
      if (nums[1] !== undefined && nums[1] !== s.discomCount) {
        problems.push(`${rel}: hero claims ${nums[1]} DISCOMs, database has ${s.discomCount}`);
      }
    }
    if (problems.length) {
      fail(`advertised coverage is out of step with the database:\n    ${[...new Set(problems)].join('\n    ')}`);
    } else {
      passed++;
      console.log(`  ✓ ${s.stateCount} states / ${s.discomCount} DISCOMs / ${s.categoryCount} categories quoted consistently`);
    }
  }
}

// ── 10. every NEW surcharge rate shows its source ─────────────────────────────
// The rates in js/tariffs/fppa.js decide real money, and provenance for them lives in one
// free-text `source` string — so a figure read off the regulator's order and one read off a
// news report look identical. 26 of the 32 entries carry no order URL at all.
//
// Backfilling those is research, not code, so they are grandfathered below by name. The point
// of this group is that the list may only ever shrink: any entry added from today has to carry
// a sourceUrl and a verifiedOn, and an entry that gains one must be struck off the list. That
// stops the gap growing while the backfill happens at whatever pace it happens.
console.log('\n• new surcharge rates carry provenance');
{
  const GRANDFATHERED = new Set([
    'state:Uttar Pradesh:2026-08-01', 'state:Uttar Pradesh:2026-07-01',
    'state:Uttar Pradesh:2026-06-01', 'state:Uttar Pradesh:2026-05-01',
    'state:Uttar Pradesh:2026-04-01', 'state:Uttar Pradesh:2026-03-01',
    'state:Uttar Pradesh:2026-02-01', 'state:Uttar Pradesh:2026-01-01',
    'state:Uttar Pradesh:2025-12-01', 'state:Uttar Pradesh:2025-11-01',
    'state:Uttar Pradesh:2025-10-01', 'state:Uttar Pradesh:2025-09-01',
    'state:Uttar Pradesh:2025-08-01', 'state:Uttar Pradesh:2025-07-01',
    'state:Uttar Pradesh:2025-06-01', 'state:Uttar Pradesh:2025-05-01',
    'state:Uttar Pradesh:2025-04-01',
    'discom:brpl:2025-05-09',  'discom:brpl:2025-07-01',
    'discom:bypl:2025-05-09',  'discom:bypl:2025-07-01',
    'discom:tpddl:2025-05-09', 'discom:tpddl:2025-07-01',
    'discom:jvvnl:2025-10-01', 'discom:avvnl:2025-10-01', 'discom:jdvvnl:2025-10-01',
  ]);

  const FPPA = await import(pathToFileURL(path.join(ROOT, 'js', 'tariffs', 'fppa.js')).href);
  const entries = [
    ...Object.entries(FPPA.FPPA_BY_STATE).flatMap(([k, l]) => l.map(e => ['state', k, e])),
    ...Object.entries(FPPA.FPPA_BY_DISCOM).flatMap(([k, l]) => l.map(e => ['discom', k, e])),
  ];

  const problems = [];
  for (const [scope, key, e] of entries) {
    const id = scope + ':' + key + ':' + e.from;
    const sourced = !!e.sourceUrl && !!e.verifiedOn;
    if (sourced) {
      // A rate that has since been sourced must leave the list, or the list stops meaning much.
      if (GRANDFATHERED.has(id)) problems.push(id + ' — now sourced; remove it from GRANDFATHERED');
      continue;
    }
    if (GRANDFATHERED.has(id)) continue;
    const missing = [!e.sourceUrl && 'sourceUrl', !e.verifiedOn && 'verifiedOn'].filter(Boolean);
    problems.push(id + ' — new rate, missing ' + missing.join(' + '));
  }
  // An entry that no longer exists should not linger on the list either.
  const ids = new Set(entries.map(([s, k, e]) => s + ':' + k + ':' + e.from));
  for (const id of GRANDFATHERED) if (!ids.has(id)) problems.push(id + ' — gone from fppa.js; remove it from GRANDFATHERED');

  if (problems.length) {
    fail('surcharge rates need a source:\n    ' + problems.join('\n    '));
  } else {
    passed++;
    console.log('  ✓ ' + (entries.length - GRANDFATHERED.size) + '/' + entries.length
      + ' rates carry an order URL + verification date; ' + GRANDFATHERED.size + ' grandfathered, none added');
  }
}

// ── 11. a page that claims a breadcrumb trail shows one ───────────────────────
// The BreadcrumbList JSON-LD tells Google the page sits in a hierarchy. If no visible nav
// carries the same trail, that is a claim the page does not honour - and it cost readers the
// one control that gets them back up a level. Eight pages had drifted that way.
{
  const problems = [];
  for (const rel of htmlPages) {
    const html = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    const m = [...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)]
      .map(x => x[1]).find(x => x.includes('BreadcrumbList'));
    if (!m) continue;
    let names;
    try { names = JSON.parse(m).itemListElement.map(i => i.name); } catch { continue; }
    const nav = /<nav class="seo-breadcrumbs"[\s\S]*?<\/nav>/.exec(html);
    if (!nav) { problems.push(rel + ' — declares a BreadcrumbList but shows no trail'); continue; }
    const shown = nav[0].replace(/<[^>]+>/g, ' ').replace(/&[a-z]+;/g, ' ')
      .split('›').map(t => t.replace(/\s+/g, ' ').trim()).filter(Boolean);
    // The visible trail may translate at runtime, so compare shape, not every word: same
    // number of steps, and the last one naming the page the JSON-LD ends on.
    if (shown.length !== names.length) {
      problems.push(`${rel} — trail has ${shown.length} steps, JSON-LD declares ${names.length}`);
    }
  }
  if (problems.length) fail('breadcrumbs:\n    ' + problems.join('\n    '));
  else { passed++; console.log('  ✓ every page declaring a BreadcrumbList shows a matching trail'); }
}

// ── 12. every indexable page is declared in the sitemap ──────────────────────
// /understand-your-bill/ and its three twins were indexable, self-canonical and linked from
// the footer of all 509 pages — and absent from sitemap.xml. Nothing failed, because nothing
// looked. This inverts the check: start from what is on disk, not from what the route table
// remembers. A page that is deliberately undeclared must say so via noindex or a canonical
// pointing elsewhere — which is exactly what the existing exclusions already do.
{
  const sitemap = fs.readFileSync(path.join(ROOT, 'sitemap.xml'), 'utf8');
  const ORIGIN = 'https://thediscombill.com';
  const declared = new Set();
  // <loc> carries the canonical URL; xhtml:link carries each hreflang twin as an attribute.
  // Both count as declared — a twin reachable only through its parent's alternate set is
  // still a URL we have handed to Google.
  for (const m of sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)) declared.add(m[1].trim());
  for (const m of sitemap.matchAll(/href="([^"]+)"/g)) declared.add(m[1].trim());

  const missing = [];
  for (const rel of htmlPages) {
    if (!rel.endsWith('index.html')) continue;         // 404.html, verification stubs
    const html = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    if (/<meta[^>]+name="robots"[^>]+noindex/i.test(html)) continue;
    const url = ORIGIN + '/' + rel.slice(0, -'index.html'.length);
    const canon = /<link[^>]+rel="canonical"[^>]+href="([^"]+)"/i.exec(html);
    // Canonicalised elsewhere → correctly excluded, e.g. /fuel-surcharge/ → /fppa/.
    if (canon && canon[1].replace(/\/?$/, '/') !== url) continue;
    if (!declared.has(url)) missing.push(url.slice(ORIGIN.length));
  }
  if (missing.length) {
    fail(`indexable but absent from sitemap.xml:\n    ` + missing.join('\n    '));
  } else {
    passed++;
    console.log(`  ✓ all ${htmlPages.length} pages: every indexable one is declared in sitemap.xml`);
  }
}

// ── 13. the homepage sample bills still come out of the engine ────────────────
// The hero rotates five DISCOM bills whose every figure is calculateBill() output. They were
// verified once by hand, and index.html carries a comment telling the next person to
// "re-verify every slide after any tariff order" — a manual step with nothing behind it. A
// tariff update could silently leave five wrong bills on the most-visited page on the site.
// Now it fails here instead.
//
// The five parameter sets are the ones the comment in index.html documents: 250 units, 2 kW,
// 30 days, 2026-07-15, each DISCOM at its own documented surcharge (UP FPPAS -4.43%, BRPL
// PPAC 17.94%; BESCOM, MSEDCL and TNPDCL have none on record). MVVNL is ST-10B, NOT ST-10A,
// which caps at 1 kW / 100 units and cannot produce a 250-unit bill at all.
console.log('\n• homepage sample bills match the engine');
{
  const { ensureAll } = await import(pathToFileURL(path.join(ROOT, 'js', 'tariffs', 'registry.js')).href);
  const { calculateBill } = await import(pathToFileURL(path.join(ROOT, 'js', 'engine.js')).href);
  await ensureAll();

  const BASE = { categoryId: 'domestic', units: 250, connectedLoadKw: 2, billingPeriodDays: 30, billingDate: '2026-07-15' };
  const SLIDES = [
    ['UPPCL · Lucknow',      { discomId: 'mvvnl', supplyTypeId: '10B', facRate: -4.43, facMode: 'percent' }],
    ['BSES Rajdhani · Delhi',{ discomId: 'brpl', facRate: 17.94, facMode: 'percent' }],
    ['BESCOM · Bengaluru',   { discomId: 'bescom' }],
    ['MSEDCL · Maharashtra', { discomId: 'msedcl' }],
    ['TNPDCL · Tamil Nadu',  { discomId: 'tangedco' }],
  ];

  const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  const shown = [...html.matchAll(/<span class="hbc-hero-amount">₹([\d,]+)<\/span>/g)].map((m) => Number(m[1].replace(/,/g, '')));
  const problems = [];

  if (shown.length !== SLIDES.length) {
    problems.push(`index.html shows ${shown.length} sample bills, this check knows ${SLIDES.length} — add the new slide's parameters here`);
  } else {
    for (let i = 0; i < SLIDES.length; i++) {
      const [label, params] = SLIDES[i];
      let net;
      try { net = calculateBill({ ...BASE, ...params }).currentNet; }
      catch (err) { problems.push(`${label}: calculateBill threw — ${err.message}`); continue; }
      if (Math.round(net) !== shown[i]) {
        problems.push(`${label}: homepage shows ₹${shown[i].toLocaleString('en-IN')}, engine now returns ₹${Math.round(net).toLocaleString('en-IN')}`);
      }
    }
  }

  if (problems.length) {
    fail(`homepage hero bills are out of step with the engine:\n    ${problems.join('\n    ')}`);
  } else {
    passed++;
    console.log(`  ✓ all ${SLIDES.length} hero sample bills reproduce from calculateBill()`);
  }
}

// ── summary ───────────────────────────────────────────────────────────────────
console.log(`\n${failed ? '✗' : '✓'} site checks — ${passed} groups passed, ${failed} failures\n`);
process.exit(failed ? 1 : 0);
