// tests/site.test.mjs — dependency-free integrity checks over the generated static site.
// Run with:  node tests/site.test.mjs
//
// The site is 445 hand-cross-linked pages generated by generate-seo.js. Two things rot
// silently there and neither the engine tests nor the eye catch them:
//   1. Internal links to pages/assets that don't exist (a renamed slug, a dropped route).
//   2. SEO pages missing the structural essentials (title, single H1, canonical).
// This walks the built tree and fails on either. Run after `npm run seo`.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const IGNORE = new Set(['node_modules', '.git', 'dist', '.wrangler', 'graphify-out', 'supabase']);

let passed = 0, failed = 0;
const fail = (msg) => { failed++; console.error(`  ✗ ${msg}`); };

// ── collect every file + the .html pages ──────────────────────────────────────
const files = new Set();     // repo-relative, forward slashes
const htmlPages = [];
(function walk(dir) {
  for (const name of fs.readdirSync(dir)) {
    if (IGNORE.has(name)) continue;
    const abs = path.join(dir, name);
    const rel = path.relative(ROOT, abs).replace(/\\/g, '/');
    if (fs.statSync(abs).isDirectory()) walk(abs);
    else { files.add(rel); if (rel.endsWith('.html')) htmlPages.push(rel); }
  }
})(ROOT);

// Resolve an internal link target to a repo-relative file; return null if unresolvable form.
function resolveTarget(href, fromFile) {
  let t = href.split('#')[0].split('?')[0];
  if (!t) return null;                                  // pure #fragment / query → same page
  if (t.startsWith('/')) t = t.slice(1);                // root-absolute
  else t = path.posix.join(path.posix.dirname(fromFile), t);  // relative to the page
  t = t.replace(/\/$/, '');                             // trim trailing slash
  return t;                                             // '' means site root
}
function targetExists(t) {
  if (t === '') return files.has('index.html');
  return files.has(t) || files.has(`${t}/index.html`) || files.has(`${t}.html`);
}

// ── 1. internal-link integrity ────────────────────────────────────────────────
console.log('\n• internal-link integrity');
const broken = new Map();   // "page → href" dedup
for (const page of htmlPages) {
  const html = fs.readFileSync(path.join(ROOT, page), 'utf8');
  const links = [...html.matchAll(/(?:href|src)="([^"]+)"/g)].map(m => m[1]);
  for (const href of links) {
    if (/^(https?:|mailto:|tel:|data:|javascript:|\/\/|#)/.test(href)) continue;   // external/inline/anchor
    const t = resolveTarget(href, page);
    if (t === null) continue;
    if (!targetExists(t)) broken.set(`${page}  →  ${href}`, true);
  }
}
if (broken.size) { for (const k of broken.keys()) fail(`broken link: ${k}`); }
else { passed++; console.log(`  ✓ all internal links resolve (${htmlPages.length} pages scanned)`); }

// ── 2. SEO-page structure (generated content pages only) ──────────────────────
console.log('\n• SEO page structure');
const SEO = /^(guides|tariffs|glossary|smart-meter-recharge|hi|mr|ta)\//;
let seoChecked = 0, seoBad = 0;
for (const page of htmlPages) {
  if (!SEO.test(page)) continue;
  seoChecked++;
  const html = fs.readFileSync(path.join(ROOT, page), 'utf8');
  const h1s = (html.match(/<h1[ >]/g) || []).length;
  const probs = [];
  if (!/<title>[^<]+<\/title>/.test(html)) probs.push('missing <title>');
  if (h1s !== 1) probs.push(`${h1s} <h1> (want 1)`);
  if (!/<link rel="canonical"/.test(html)) probs.push('missing canonical');
  if (probs.length) { seoBad++; fail(`${page}: ${probs.join(', ')}`); }
}
if (!seoBad) { passed++; console.log(`  ✓ title / single-H1 / canonical present (${seoChecked} SEO pages)`); }

// ── summary ───────────────────────────────────────────────────────────────────
console.log(`\n${failed ? '✗' : '✓'} site checks — ${passed} groups passed, ${failed} failures\n`);
process.exit(failed ? 1 : 0);
