// js/tariffs/index.js
// GENERATED by scripts/build-tariff-index.mjs — do not edit. Update the per-state files
// and run `npm run seo`.
//
// The index half of the tariff registry: which states and DISCOMs exist, plus every cheap
// field about them. The slab/charge tables (`categories`) are deliberately NOT here — they
// are ~93% of the data and registry.js imports them per state, on demand.

/** Map of state name -> slug of its data module, e.g. "Uttar Pradesh" -> "uttar-pradesh". */
export const STATE_SLUG = {
    "Andhra Pradesh": "andhra-pradesh",
    "Arunachal Pradesh": "arunachal-pradesh",
    "Assam": "assam",
    "Bihar": "bihar",
    "Chandigarh": "chandigarh",
    "Chhattisgarh": "chhattisgarh",
    "Dadra & Nagar Haveli and Daman & Diu": "dadra-and-nagar-haveli-and-daman-and-diu",
    "Delhi": "delhi",
    "Goa": "goa",
    "Gujarat": "gujarat",
    "Haryana": "haryana",
    "Himachal Pradesh": "himachal-pradesh",
    "Jammu & Kashmir": "jammu-and-kashmir",
    "Jharkhand": "jharkhand",
    "Karnataka": "karnataka",
    "Kerala": "kerala",
    "Ladakh": "ladakh",
    "Madhya Pradesh": "madhya-pradesh",
    "Maharashtra": "maharashtra",
    "Manipur": "manipur",
    "Meghalaya": "meghalaya",
    "Mizoram": "mizoram",
    "Nagaland": "nagaland",
    "Odisha": "odisha",
    "Puducherry": "puducherry",
    "Punjab": "punjab",
    "Rajasthan": "rajasthan",
    "Sikkim": "sikkim",
    "Tamil Nadu": "tamil-nadu",
    "Telangana": "telangana",
    "Tripura": "tripura",
    "Uttar Pradesh": "uttar-pradesh",
    "Uttarakhand": "uttarakhand",
    "West Bengal": "west-bengal"
  };

/** State-level metadata (everything the state module exports except `discoms`). */
export const STATE_INFO = {
    "Andhra Pradesh": {
      "state": "Andhra Pradesh",
      "ratesAsOf": "FY 2026-27 (APERC retail supply tariff order — FY 2025-26 schedule retained, no hike)",
      "sourceUrl": "https://aperc.gov.in"
    },
    "Arunachal Pradesh": {
      "state": "Arunachal Pradesh"
    },
    "Assam": {
      "state": "Assam",
      "ratesAsOf": "AERC order dt. 25-Mar-2025, w.e.f. 1 April 2025 (APDCL petitioned to continue it unchanged for FY 2026-27)",
      "sourceUrl": "https://aerc.gov.in"
    },
    "Bihar": {
      "state": "Bihar",
      "currentRatesFrom": "2026-04-01",
      "ratesAsOf": "FY 2026-27 (BERC order dt. 18-03-2026)",
      "sourceUrl": "https://berc.co.in/images/pdf/tariff-order/2026-27/Tariff_Chart_FY_2026-27.pdf"
    },
    "Chandigarh": {
      "state": "Chandigarh",
      "ratesAsOf": "FY 2026-27 (JERC MYT order for CPDL, FY 2025-26 to FY 2029-30 — FY 2026-27 rates approved in advance)",
      "sourceUrl": "https://jercuts.gov.in/order_category/chandigarh/"
    },
    "Chhattisgarh": {
      "state": "Chhattisgarh",
      "ratesAsOf": "FY 2026-27 (CSERC Tariff Schedule for FY 2026-27, applicable from 01-Jul-2026)",
      "sourceUrl": "https://cserc.gov.in"
    },
    "Dadra & Nagar Haveli and Daman & Diu": {
      "state": "Dadra & Nagar Haveli and Daman & Diu"
    },
    "Delhi": {
      "state": "Delhi",
      "ratesAsOf": "FY 2025-26 (DERC schedule; PPAC monthly, see fppa.js)",
      "sourceUrl": "https://www.derc.gov.in/tarriff-orders",
      "excessDemand": {
        "multiplier": 0.3,
        "tolerancePct": 0
      }
    },
    "Goa": {
      "state": "Goa",
      "ratesAsOf": "FY 2026-27 (JERC 4th MYT Control Period order, FY 2025-26 to FY 2029-30 — FY 2026-27 rates approved in advance)",
      "sourceUrl": "https://www.goaelectricity.gov.in"
    },
    "Gujarat": {
      "state": "Gujarat",
      "excessDemand": {
        "rate": 360,
        "tolerancePct": 0
      },
      "ratesAsOf": "FY 2026-27 (GERC orders dt. 25-Mar-2026, rates retained)",
      "sourceUrl": "https://gercin.org/order-category/tariff-orders/"
    },
    "Haryana": {
      "state": "Haryana",
      "ratesAsOf": "FY 2026-27 (HERC order dt. 28-Mar-2025; tariff retained unchanged for FY 2026-27)",
      "sourceUrl": "https://herc.gov.in"
    },
    "Himachal Pradesh": {
      "state": "Himachal Pradesh",
      "ratesAsOf": "FY 2026-27 (HPERC Tariff Order for HPSEBL, in force from 01-Apr-2026)",
      "sourceUrl": "https://hperc.org"
    },
    "Jammu & Kashmir": {
      "state": "Jammu & Kashmir",
      "ratesAsOf": "FY 2025-26 (JERC for the UT of J&K and Ladakh — JPDCL & KPDCL ARR and Tariff for FY 2025-26)",
      "sourceUrl": "https://www.jpdcl.co.in/downloads/tariff/JPDCL_KPDCL_Tariff_Order_2025_26.pdf"
    },
    "Jharkhand": {
      "state": "Jharkhand",
      "ratesAsOf": "FY 2026-27 (JSERC tariff determination for FY 2026-27, first year of the FY 2026-27 to FY 2030-31 control period)",
      "sourceUrl": "https://jserc.org/tariff.aspx"
    },
    "Karnataka": {
      "state": "Karnataka",
      "excessDemand": {
        "multiplier": 1.5,
        "tolerancePct": 0
      },
      "currentRatesFrom": "2026-04-01",
      "ratesAsOf": "FY 2026-27 (KERC Tariff Order 2025, dt. 27-03-2025)",
      "sourceUrl": "https://kerc.karnataka.gov.in/uploads/96731743148968.pdf"
    },
    "Kerala": {
      "state": "Kerala",
      "ratesAsOf": "In force to 31-Mar-2027 (KSERC Order 427/D(T)/2023 dt. 05-Dec-2024, rates w.e.f. 01-Apr-2025)",
      "sourceUrl": "https://erckerala.org/orderpage"
    },
    "Ladakh": {
      "state": "Ladakh"
    },
    "Madhya Pradesh": {
      "state": "Madhya Pradesh",
      "ratesAsOf": "FY 2026-27 (MPERC Retail Supply Tariff Order for FY 2026-27, Annexure-2)",
      "sourceUrl": "https://mperc.in"
    },
    "Maharashtra": {
      "state": "Maharashtra",
      "excessDemand": {
        "multiplier": 1.5,
        "tolerancePct": 0
      }
    },
    "Manipur": {
      "state": "Manipur"
    },
    "Meghalaya": {
      "state": "Meghalaya",
      "ratesAsOf": "FY 2026-27 (MSERC Order in Case No. 11 of 2025, dated 26-03-2026)",
      "sourceUrl": "https://mserc.gov.in/tarifforders.html"
    },
    "Mizoram": {
      "state": "Mizoram"
    },
    "Nagaland": {
      "state": "Nagaland"
    },
    "Odisha": {
      "state": "Odisha",
      "currentRatesFrom": "2024-04-01",
      "ratesAsOf": "FY 2026-27 (OERC RST Order dt. 24-03-2026 — FY 2024-25 rates retained)",
      "sourceUrl": "https://www.orierc.org/CuteSoft_Client/writereaddata/upload/DISCOM_TARIFF_ORDER_FY_2026-27.pdf"
    },
    "Puducherry": {
      "state": "Puducherry",
      "ratesAsOf": "FY 2026-27 (JERC 4th MYT Control Period order for the Electricity Department of Puducherry, Table 9-2)",
      "sourceUrl": "https://jercuts.gov.in/order_category/puducherry/"
    },
    "Punjab": {
      "state": "Punjab",
      "ratesAsOf": "FY 2026-27 (PSERC tariff order for PSPCL, w.e.f. 01-Apr-2026)",
      "sourceUrl": "https://pserc.gov.in/pages/tariff-orders.html"
    },
    "Rajasthan": {
      "state": "Rajasthan",
      "ratesAsOf": "Tariff for Supply of Electricity-2025 (RERC Petitions 2303–2305/2025, in force from 01-Oct-2025)",
      "sourceUrl": "https://rerc.rajasthan.gov.in",
      "currentRatesFrom": "2025-10-01"
    },
    "Sikkim": {
      "state": "Sikkim",
      "ratesAsOf": "FY 2025-26 (SSERC Tariff Order for the F.Y. 2025-26)",
      "sourceUrl": "https://selfservice.powersikkim.in/assets/home/Tariff-Schedule-FY-2025-26.pdf"
    },
    "Tamil Nadu": {
      "state": "Tamil Nadu",
      "excessDemand": {
        "pctEnergyPerKw": 1,
        "tolerancePct": 0
      },
      "currentRatesFrom": "2025-07-01",
      "ratesAsOf": "FY 2025-26 (TNERC T.O. No.6 of 2025)",
      "sourceUrl": "https://www.tnerc.tn.gov.in/Orders/files/TO-Order%20No6300620252131.pdf"
    },
    "Telangana": {
      "state": "Telangana",
      "ratesAsOf": "FY 2026-27 (TGERC order dt. 30-Mar-2026, retail rates retained)",
      "sourceUrl": "https://www.tgerc.telangana.gov.in"
    },
    "Tripura": {
      "state": "Tripura",
      "ratesAsOf": "FY 2026-27 (TERC Tariff Order for TSECL, Annexure 2 — revised tariffs effective 01-May-2026)",
      "sourceUrl": "https://terc.tripura.gov.in/tariff-order"
    },
    "Uttar Pradesh": {
      "state": "Uttar Pradesh",
      "currentRatesFrom": "2024-10-01",
      "verified": true,
      "ratesAsOf": "FY 2026-27 (UPERC order dt. 02-Jul-2026, rates retained)",
      "sourceUrl": "https://www.uperc.org"
    },
    "Uttarakhand": {
      "state": "Uttarakhand",
      "ratesAsOf": "FY 2026-27 (UERC order dt. 30-Mar-2026 — existing rates retained, UPCL's proposed hike rejected)",
      "sourceUrl": "https://uerc.uk.gov.in"
    },
    "West Bengal": {
      "state": "West Bengal"
    }
  };

/** Per-state DISCOM metadata, minus each DISCOM's `categories` tariff tables. */
export const DISCOM_INDEX = {
    "Andhra Pradesh": [
      {
        "id": "apspdcl",
        "name": "APSPDCL",
        "fullName": "Southern Power Distribution Company of Andhra Pradesh Ltd.",
        "area": "Southern AP (Kurnool, Nandyal, Nellore, Prakasam, Chittoor, Kadapa, Annamayya, Tirupati, Sri Sathya Sai)",
        "tariffYear": "2026-27",
        "website": "https://www.apspdcl.in"
      },
      {
        "id": "apepdcl",
        "name": "APEPDCL",
        "fullName": "Eastern Power Distribution Company of Andhra Pradesh Ltd.",
        "area": "Eastern AP (Visakhapatnam, Anakapalli, Vizianagaram, Srikakulam, Parvathipuram Manyam, Alluri Sitharama Raju, Kakinada, East Godavari, Konaseema, West Godavari)",
        "tariffYear": "2026-27",
        "website": "https://www.apepdcl.in"
      }
    ],
    "Arunachal Pradesh": [
      {
        "id": "appdcl",
        "name": "APPDCL / Dept. of Power",
        "fullName": "Arunachal Pradesh Power Distribution Corporation Ltd.",
        "area": "Entire Arunachal Pradesh",
        "tariffYear": "2024-25",
        "website": "https://appdcl.in"
      }
    ],
    "Assam": [
      {
        "id": "apdcl",
        "name": "APDCL",
        "fullName": "Assam Power Distribution Company Ltd.",
        "area": "Entire Assam",
        "tariffYear": "2025-26",
        "website": "https://www.apdcl.org"
      }
    ],
    "Bihar": [
      {
        "id": "nbpdcl",
        "name": "NBPDCL",
        "fullName": "North Bihar Power Distribution Company Ltd.",
        "area": "North Bihar (Muzaffarpur, Darbhanga, Begusarai, Bhagalpur, Purnia, etc.)",
        "website": "https://www.nbpdcl.co.in",
        "tariffYear": "2026-27"
      },
      {
        "id": "sbpdcl",
        "name": "SBPDCL",
        "fullName": "South Bihar Power Distribution Company Ltd.",
        "area": "South Bihar (Patna, Gaya, Nalanda, Aurangabad, Rohtas, etc.)",
        "website": "https://www.sbpdcl.co.in",
        "tariffYear": "2026-27"
      }
    ],
    "Chandigarh": [
      {
        "id": "chandigarh_ed",
        "name": "CPDL (Chandigarh)",
        "fullName": "Chandigarh Power Distribution Limited",
        "area": "Chandigarh Union Territory",
        "tariffYear": "2026-27",
        "website": "https://cpdl.co.in"
      }
    ],
    "Chhattisgarh": [
      {
        "id": "cspdcl",
        "name": "CSPDCL",
        "fullName": "Chhattisgarh State Power Distribution Company Ltd.",
        "area": "Entire Chhattisgarh",
        "tariffYear": "2026-27",
        "website": "https://www.cspdcl.co.in"
      }
    ],
    "Dadra & Nagar Haveli and Daman & Diu": [
      {
        "id": "dnhpdcl",
        "name": "DNHPDCL",
        "fullName": "DNH Power Distribution Corporation Ltd.",
        "area": "Dadra & Nagar Haveli and Daman & Diu",
        "tariffYear": "2024-25",
        "website": "https://www.dnhpdcl.co.in"
      }
    ],
    "Delhi": [
      {
        "id": "brpl",
        "name": "BRPL (BSES Rajdhani)",
        "fullName": "BSES Rajdhani Power Ltd.",
        "area": "South & West Delhi",
        "tariffYear": "2025-26",
        "website": "https://www.bsesdelhi.com"
      },
      {
        "id": "bypl",
        "name": "BYPL (BSES Yamuna)",
        "fullName": "BSES Yamuna Power Ltd.",
        "area": "East & Central Delhi",
        "tariffYear": "2025-26",
        "website": "https://www.bsesdelhi.com"
      },
      {
        "id": "tpddl",
        "name": "Tata Power-DDL (TPDDL)",
        "fullName": "Tata Power Delhi Distribution Ltd.",
        "area": "North & North-West Delhi",
        "tariffYear": "2025-26",
        "website": "https://www.tatapower-ddl.com"
      },
      {
        "id": "ndmc_delhi",
        "name": "NDMC",
        "fullName": "New Delhi Municipal Council",
        "area": "Lutyens' Delhi (Central Government area)",
        "tariffYear": "2025-26",
        "website": "https://www.ndmc.gov.in"
      }
    ],
    "Goa": [
      {
        "id": "ged",
        "name": "Goa Electricity Dept.",
        "fullName": "Electricity Department, Government of Goa",
        "area": "Entire Goa",
        "tariffYear": "2026-27",
        "website": "https://www.goaelectricity.gov.in"
      }
    ],
    "Gujarat": [
      {
        "id": "ugvcl",
        "name": "UGVCL",
        "fullName": "Uttar Gujarat Vij Company Ltd.",
        "area": "North Gujarat (Mehsana, Patan, Banaskantha, Sabarkantha, Gandhinagar, Aravalli)",
        "tariffYear": "2026-27",
        "website": "https://www.ugvcl.com"
      },
      {
        "id": "mgvcl",
        "name": "MGVCL",
        "fullName": "Madhya Gujarat Vij Company Ltd.",
        "area": "Central Gujarat (Vadodara, Anand, Kheda, Panchmahal, Dahod, Chhota Udaipur)",
        "tariffYear": "2026-27",
        "website": "https://www.mgvcl.com"
      },
      {
        "id": "pgvcl",
        "name": "PGVCL",
        "fullName": "Paschim Gujarat Vij Company Ltd.",
        "area": "Saurashtra & Kutch (Rajkot, Jamnagar, Junagadh, Porbandar, Bhavnagar, Amreli, Kutch, Surendranagar, Morbi)",
        "tariffYear": "2026-27",
        "website": "https://www.pgvcl.com"
      },
      {
        "id": "dgvcl",
        "name": "DGVCL",
        "fullName": "Dakshin Gujarat Vij Company Ltd.",
        "area": "South Gujarat (Surat, Bharuch, Narmada, Navsari, Valsad, Tapi, Dang)",
        "tariffYear": "2026-27",
        "website": "https://www.dgvcl.com"
      }
    ],
    "Haryana": [
      {
        "id": "dhbvn",
        "name": "DHBVN",
        "fullName": "Dakshin Haryana Bijli Vitran Nigam Ltd.",
        "area": "South Haryana (Gurugram, Faridabad, Rewari, Mahendragarh, Nuh, Palwal, Bhiwani, Hisar, Sirsa, Fatehabad, Jind, Narnaul)",
        "tariffYear": "2026-27",
        "website": "https://www.dhbvn.org.in"
      },
      {
        "id": "uhbvn",
        "name": "UHBVN",
        "fullName": "Uttar Haryana Bijli Vitran Nigam Ltd.",
        "area": "North Haryana (Panchkula, Ambala, Yamunanagar, Kurukshetra, Karnal, Panipat, Sonipat, Rohtak, Jhajjar, Kaithal)",
        "tariffYear": "2026-27",
        "website": "https://www.uhbvn.org.in"
      }
    ],
    "Himachal Pradesh": [
      {
        "id": "hpsebl",
        "name": "HPSEBL",
        "fullName": "Himachal Pradesh State Electricity Board Ltd.",
        "area": "Entire Himachal Pradesh",
        "tariffYear": "2026-27",
        "website": "https://www.hpseb.in"
      }
    ],
    "Jammu & Kashmir": [
      {
        "id": "jkpdd_jammu",
        "name": "JPDCL (Jammu Region)",
        "fullName": "Jammu Power Distribution Corporation Ltd.",
        "area": "Jammu, Samba, Kathua, Udhampur, Reasi, Ramban, Doda, Kishtwar, Rajouri, Poonch",
        "tariffYear": "2025-26",
        "website": "https://www.jpdcl.co.in"
      },
      {
        "id": "jkpdd_kashmir",
        "name": "KPDCL (Kashmir Region)",
        "fullName": "Kashmir Power Distribution Corporation Ltd.",
        "area": "Srinagar, Baramulla, Anantnag, Pulwama, Kupwara, Budgam, Ganderbal, Bandipora, Shopian, Kulgam",
        "tariffYear": "2025-26",
        "website": "https://kpdcl.jk.gov.in"
      }
    ],
    "Jharkhand": [
      {
        "id": "jbvnl",
        "name": "JBVNL",
        "fullName": "Jharkhand Bijli Vitran Nigam Ltd.",
        "area": "Entire Jharkhand",
        "tariffYear": "2026-27",
        "website": "https://jbvnl.co.in"
      }
    ],
    "Karnataka": [
      {
        "id": "bescom",
        "name": "BESCOM",
        "fullName": "Bangalore Electricity Supply Company Ltd.",
        "area": "Bangalore Urban, Bangalore Rural, Tumkur, Kolar, Chikkaballapur, Ramanagara, Chitradurga",
        "website": "https://www.bescom.co.in",
        "tariffYear": "2026-27"
      },
      {
        "id": "mescom",
        "name": "MESCOM",
        "fullName": "Mangalore Electricity Supply Company Ltd.",
        "area": "Dakshina Kannada, Udupi, Shivamogga, Kodagu, Chikkamagaluru",
        "website": "https://www.mescom.co.in",
        "tariffYear": "2026-27"
      },
      {
        "id": "cesc_karnataka",
        "name": "CESC Mysuru",
        "fullName": "Chamundeshwari Electricity Supply Corporation Ltd.",
        "area": "Mysuru, Mandya, Hassan, Chamarajanagar",
        "website": "https://cescmysore.karnataka.gov.in",
        "tariffYear": "2026-27"
      },
      {
        "id": "gescom",
        "name": "GESCOM",
        "fullName": "Gulbarga Electricity Supply Company Ltd.",
        "area": "Kalaburagi, Bidar, Yadgir, Raichur, Koppal",
        "website": "https://www.gescom.karnataka.gov.in",
        "tariffYear": "2026-27"
      },
      {
        "id": "hescom",
        "name": "HESCOM",
        "fullName": "Hubli Electricity Supply Company Ltd.",
        "area": "Dharwad, Gadag, Haveri, Belagavi, Uttara Kannada, Ballari, Vijayanagara",
        "website": "https://www.hescom.co.in",
        "tariffYear": "2026-27"
      }
    ],
    "Kerala": [
      {
        "id": "kseb",
        "name": "KSEB",
        "fullName": "Kerala State Electricity Board Ltd.",
        "area": "Entire Kerala",
        "tariffYear": "2026-27",
        "website": "https://www.kseb.in"
      }
    ],
    "Ladakh": [
      {
        "id": "lpdcl",
        "name": "LPDCL / Ladakh Power Dept.",
        "fullName": "Ladakh Power Development Corp. / Power Development Dept., Ladakh",
        "area": "Leh, Kargil districts",
        "tariffYear": "2024-25",
        "website": "https://ladakh.gov.in"
      }
    ],
    "Madhya Pradesh": [
      {
        "id": "mppkvvcl",
        "name": "MPPKVVCL",
        "fullName": "Madhya Pradesh Paschim Kshetra Vidyut Vitaran Company Ltd.",
        "area": "West MP (Indore, Ujjain, Ratlam, Mandsaur, Dewas, Khandwa, Khargone, Dhar)",
        "tariffYear": "2026-27",
        "website": "https://www.mpwz.co.in"
      },
      {
        "id": "mpmkvvcl",
        "name": "MPMKVVCL",
        "fullName": "Madhya Pradesh Madhya Kshetra Vidyut Vitaran Company Ltd.",
        "area": "Central MP (Bhopal, Sagar, Rewa, Satna, Narsinghpur, Narmadapuram, Raisen, Vidisha, Gwalior, Guna)",
        "tariffYear": "2026-27",
        "website": "https://portal.mpcz.in"
      },
      {
        "id": "mpez",
        "name": "MPEZ",
        "fullName": "Madhya Pradesh Poorv Kshetra Vidyut Vitaran Company Ltd.",
        "area": "East MP (Jabalpur, Chhindwara, Seoni, Mandla, Balaghat, Dindori, Shahdol)",
        "tariffYear": "2026-27",
        "website": "https://mpez.co.in"
      }
    ],
    "Maharashtra": [
      {
        "id": "msedcl",
        "name": "MSEDCL",
        "fullName": "Maharashtra State Electricity Distribution Co. Ltd.",
        "area": "Maharashtra (except Mumbai city area served by Adani/BEST/Tata Power)",
        "tariffYear": "2026-27",
        "website": "https://www.mahadiscom.in",
        "sourceUrl": "https://www.mahadiscom.in/consumer/wp-content/uploads/2025/08/MSEDCL-MYT-Order_Case_no_217-of-2024.pdf",
        "ratesAsOf": "FY 2026-27 (MERC Case 217/2024)"
      },
      {
        "id": "adani_mumbai",
        "name": "Adani Electricity Mumbai",
        "fullName": "Adani Electricity Mumbai Ltd. (formerly Reliance Infrastructure)",
        "area": "Mumbai suburbs (Bandra, Andheri, Kurla, Borivali, Malad, etc.)",
        "tariffYear": "2026-27",
        "website": "https://www.adanielectricity.com",
        "sourceUrl": "https://merc.gov.in/wp-content/uploads/2025/03/Press-Note_MYT-Order_AEML_English.pdf",
        "ratesAsOf": "FY 2026-27 (MERC Case 211/2024)"
      },
      {
        "id": "best_mumbai",
        "name": "BEST Mumbai",
        "fullName": "Brihanmumbai Electricity Supply and Transport (BEST)",
        "area": "Mumbai Island City (South Mumbai – Colaba to Mahim/Sion)",
        "tariffYear": "2026-27",
        "website": "https://www.bestundertaking.com",
        "sourceUrl": "https://merc.gov.in/wp-content/uploads/2025/03/Press-Note_MYT-Order_BEST_English.pdf",
        "ratesAsOf": "FY 2026-27 (MERC Case 207/2024)"
      },
      {
        "id": "tata_power_mumbai",
        "name": "Tata Power Mumbai",
        "fullName": "Tata Power Company Ltd. – Mumbai Distribution",
        "area": "Parts of Mumbai (Dharavi, Wadala, parts of Kurla, Chembur, etc.)",
        "tariffYear": "2026-27",
        "website": "https://www.tatapower.com",
        "sourceUrl": "https://merc.gov.in/wp-content/uploads/2025/03/Press-Note_MYT-Order_TPC_English.pdf",
        "ratesAsOf": "FY 2026-27 (MERC Case 210/2024)"
      }
    ],
    "Manipur": [
      {
        "id": "mspdcl",
        "name": "MSPDCL",
        "fullName": "Manipur State Power Distribution Company Ltd.",
        "area": "Entire Manipur",
        "tariffYear": "2024-25",
        "website": "https://www.mspdcl.com"
      }
    ],
    "Meghalaya": [
      {
        "id": "mepdcl",
        "name": "MePDCL",
        "fullName": "Meghalaya Power Distribution Corporation Ltd.",
        "area": "Entire Meghalaya",
        "tariffYear": "2026-27",
        "website": "https://www.mepdcl.in"
      }
    ],
    "Mizoram": [
      {
        "id": "ped_mizoram",
        "name": "P&E Dept., Mizoram",
        "fullName": "Power & Electricity Department, Government of Mizoram",
        "area": "Entire Mizoram",
        "tariffYear": "2024-25",
        "website": "https://mizoram.gov.in"
      }
    ],
    "Nagaland": [
      {
        "id": "doe_nagaland",
        "name": "DoE Nagaland",
        "fullName": "Department of Electricity, Government of Nagaland",
        "area": "Entire Nagaland",
        "tariffYear": "2024-25",
        "website": "https://nagaland.gov.in"
      }
    ],
    "Odisha": [
      {
        "id": "tpcodl",
        "name": "TPCODL",
        "fullName": "TP Central Odisha Distribution Ltd. (Tata Power)",
        "area": "Central Odisha (Bhubaneswar, Cuttack, Puri, Khordha, Jagatsinghpur, Kendrapara, Nayagarh, Angul, Dhenkanal)",
        "website": "https://www.tpcentralodisha.com",
        "tariffYear": "2026-27"
      },
      {
        "id": "tpnodl",
        "name": "TPNODL",
        "fullName": "TP Northern Odisha Distribution Ltd. (Tata Power)",
        "area": "North Odisha (Balasore, Bhadrak, Jajpur, Kendujhar, Mayurbhanj, Sundargarh)",
        "website": "https://www.tpnodl.com",
        "tariffYear": "2026-27"
      },
      {
        "id": "tpwodl",
        "name": "TPWODL",
        "fullName": "TP Western Odisha Distribution Ltd. (Tata Power)",
        "area": "West Odisha (Sambalpur, Bargarh, Boudh, Deogarh, Jharsuguda, Nuapada, Bolangir, Subarnapur)",
        "website": "https://www.tpwesternodisha.com",
        "tariffYear": "2026-27"
      },
      {
        "id": "tpsodl",
        "name": "TPSODL",
        "fullName": "TP Southern Odisha Distribution Ltd. (Tata Power)",
        "area": "South Odisha (Ganjam, Gajapati, Kandhamal, Kalahandi, Koraput, Nabarangpur, Rayagada, Malkangiri)",
        "website": "https://www.tpsouthernodisha.com",
        "tariffYear": "2026-27"
      }
    ],
    "Puducherry": [
      {
        "id": "pdicl",
        "name": "PDICL / Electricity Dept.",
        "fullName": "Puducherry Electricity Dept. / PDI Corporation Ltd.",
        "area": "Puducherry, Karaikal, Mahe, Yanam",
        "tariffYear": "2026-27",
        "website": "https://electricity.py.gov.in"
      }
    ],
    "Punjab": [
      {
        "id": "pspcl",
        "name": "PSPCL",
        "fullName": "Punjab State Power Corporation Ltd.",
        "area": "Entire Punjab (excl. Chandigarh)",
        "tariffYear": "2026-27",
        "website": "https://www.pspcl.in"
      }
    ],
    "Rajasthan": [
      {
        "id": "jvvnl",
        "name": "JVVNL",
        "fullName": "Jaipur Vidyut Vitaran Nigam Ltd.",
        "area": "Jaipur, Sikar, Jhunjhunu, Alwar, Bharatpur, Sawai Madhopur, Karauli, Dausa, Dholpur",
        "tariffYear": "2025-26",
        "website": "https://www.jaipurdiscom.com"
      },
      {
        "id": "avvnl",
        "name": "AVVNL",
        "fullName": "Ajmer Vidyut Vitaran Nigam Ltd.",
        "area": "Ajmer, Bhilwara, Nagaur, Sirohi, Jhalawar, Baran, Bundi, Kota, Chittorgarh, Udaipur, Banswara, Dungarpur, Rajsamand, Pratapgarh",
        "tariffYear": "2025-26",
        "website": "https://energy.rajasthan.gov.in/avvnl"
      },
      {
        "id": "jdvvnl",
        "name": "JdVVNL",
        "fullName": "Jodhpur Vidyut Vitaran Nigam Ltd.",
        "area": "Jodhpur, Barmer, Jaisalmer, Pali, Jalore, Bikaner, Churu, Hanumangarh, Sri Ganganagar",
        "tariffYear": "2025-26",
        "website": "https://energy.rajasthan.gov.in/jdvvnl"
      }
    ],
    "Sikkim": [
      {
        "id": "energy_sikkim",
        "name": "Energy & Power Dept., Sikkim",
        "fullName": "Energy & Power Department, Government of Sikkim",
        "area": "Entire Sikkim",
        "tariffYear": "2025-26",
        "website": "https://powersikkim.in"
      }
    ],
    "Tamil Nadu": [
      {
        "id": "tangedco",
        "name": "TNPDCL (TANGEDCO)",
        "fullName": "Tamil Nadu Power Distribution Corporation Ltd.",
        "area": "Entire Tamil Nadu",
        "tariffYear": "2025-26",
        "website": "https://www.tnpdcl.org"
      }
    ],
    "Telangana": [
      {
        "id": "tsspdcl",
        "name": "TGSPDCL",
        "fullName": "Telangana State Southern Power Distribution Company Ltd.",
        "area": "Southern Telangana (Hyderabad, Rangareddy, Mahbubnagar, Nalgonda, Medak, Sangareddy, Vikarabad, Siddipet, Nagarkurnool, Wanaparthy, Jogulamba Gadwal, Yadadri Bhuvanagiri)",
        "tariffYear": "2026-27",
        "website": "https://www.tgsouthernpower.org"
      },
      {
        "id": "tsnpdcl",
        "name": "TGNPDCL",
        "fullName": "Telangana State Northern Power Distribution Company Ltd.",
        "area": "Northern Telangana (Warangal, Karimnagar, Khammam, Adilabad, Nizamabad, Jagtial, Peddapalli, Mancherial, Nirmal, Bhadradri Kothagudem, Mahabubabad, Jayashankar Bhupalpally)",
        "tariffYear": "2026-27",
        "website": "https://tgnpdcl.in"
      }
    ],
    "Tripura": [
      {
        "id": "tsecl",
        "name": "TSECL",
        "fullName": "Tripura State Electricity Corporation Ltd.",
        "area": "Entire Tripura",
        "tariffYear": "2026-27",
        "website": "https://www.tsecl.in"
      }
    ],
    "Uttar Pradesh": [
      {
        "id": "dvvnl",
        "name": "DVVNL",
        "fullName": "Dakshinanchal Vidyut Vitaran Nigam Ltd.",
        "area": "South UP (Agra, Mathura, Aligarh, Firozabad, Hathras, Etah, Mainpuri, Etawah, Farrukhabad, Kannauj, Jhansi, Lalitpur, Jalaun, Hamirpur, Mahoba, Banda, Chitrakoot)",
        "website": "https://www.dvvnl.org",
        "tariffYear": "2026-27",
        "lpscRate": 1.5
      },
      {
        "id": "mvvnl",
        "name": "MVVNL",
        "fullName": "Madhyanchal Vidyut Vitaran Nigam Ltd.",
        "area": "Central UP (Lucknow, Sitapur, Hardoi, Unnao, Rae Bareli, Lakhimpur Kheri, Barabanki, Gonda, Balrampur, Shravasti, Bahraich)",
        "website": "https://www.mvvnl.in",
        "tariffYear": "2026-27",
        "lpscRate": 1.5
      },
      {
        "id": "pvvnl",
        "name": "PVVNL",
        "fullName": "Paschimanchal Vidyut Vitaran Nigam Ltd.",
        "area": "West UP (Meerut, Ghaziabad, Noida, Hapur, Bulandshahr, Muzaffarnagar, Saharanpur, Shamli, Baghpat, Amroha, Moradabad, Rampur, Bijnor, Pilibhit, Shahjahanpur)",
        "website": "https://www.pvvnl.org",
        "tariffYear": "2026-27",
        "lpscRate": 1.5
      },
      {
        "id": "puvvnl",
        "name": "PuVVNL",
        "fullName": "Purvanchal Vidyut Vitaran Nigam Ltd.",
        "area": "East UP (Varanasi, Prayagraj, Gorakhpur, Mirzapur, Sonbhadra, Azamgarh, Mau, Jaunpur, Bhadohi, Chandauli, Ghazipur)",
        "website": "https://www.puvvnl.com",
        "tariffYear": "2026-27",
        "lpscRate": 1.5
      },
      {
        "id": "kesco",
        "name": "KESCO",
        "fullName": "Kanpur Electricity Supply Company Ltd.",
        "area": "Kanpur city and district",
        "website": "https://www.kesco.co.in",
        "tariffYear": "2026-27",
        "lpscRate": 1.5
      }
    ],
    "Uttarakhand": [
      {
        "id": "upcl",
        "name": "UPCL",
        "fullName": "Uttarakhand Power Corporation Ltd.",
        "area": "Entire Uttarakhand",
        "tariffYear": "2026-27",
        "website": "https://www.upcl.org"
      }
    ],
    "West Bengal": [
      {
        "id": "wbsedcl",
        "name": "WBSEDCL",
        "fullName": "West Bengal State Electricity Distribution Company Ltd.",
        "area": "All of West Bengal outside the CESC and DPL licence areas",
        "tariffYear": "2025-26",
        "website": "https://www.wbsedcl.in",
        "ratesAsOf": "FY 2025-26 (WBERC tariff order, effective 01-Apr-2025, continues till further order)",
        "sourceUrl": "https://www.wbsedcl.in/irj/go/km/docs/internet/new_website/pdf/Tariff_Volumn/Gist%20of%20Tariff%20Order%202025-26_28_03.pdf"
      },
      {
        "id": "cesc_kolkata",
        "name": "CESC (Kolkata)",
        "fullName": "CESC Ltd. (Calcutta Electric Supply Corporation)",
        "area": "Kolkata city, Howrah, Hooghly (parts)",
        "tariffYear": "2025-26",
        "ratesAsOf": "WBERC order dt. 25-Mar-2025, w.e.f. 1 April 2025 (continues till further order)",
        "sourceUrl": "https://www.cesc.co.in/tariff"
      },
      {
        "id": "dpl",
        "name": "Erstwhile DPL area",
        "fullName": "Erstwhile Durgapur Projects Ltd. area — supplied by WBSEDCL",
        "area": "Durgapur industrial and urban area (billed by WBSEDCL on the frozen erstwhile-DPL schedule)",
        "tariffYear": "2025-26",
        "ratesAsOf": "WBERC order dt. 20-Mar-2025 for FY 2025-26 (schedule maintained at its 31-12-2018 level)",
        "sourceUrl": "https://www.wbsedcl.in/irj/go/km/docs/internet/new_website/pdf/Tariff_Volumn/Gist%20of%20Tariff%20Order%202025-26_28_03.pdf"
      }
    ]
  };

/** Sorted state names. */
export const STATES = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra & Nagar Haveli and Daman & Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu & Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal"
  ];

/** DISCOM id -> state name, so a DISCOM can be resolved without scanning every state. */
export const DISCOM_STATE = {
    "apspdcl": "Andhra Pradesh",
    "apepdcl": "Andhra Pradesh",
    "appdcl": "Arunachal Pradesh",
    "apdcl": "Assam",
    "nbpdcl": "Bihar",
    "sbpdcl": "Bihar",
    "chandigarh_ed": "Chandigarh",
    "cspdcl": "Chhattisgarh",
    "dnhpdcl": "Dadra & Nagar Haveli and Daman & Diu",
    "brpl": "Delhi",
    "bypl": "Delhi",
    "tpddl": "Delhi",
    "ndmc_delhi": "Delhi",
    "ged": "Goa",
    "ugvcl": "Gujarat",
    "mgvcl": "Gujarat",
    "pgvcl": "Gujarat",
    "dgvcl": "Gujarat",
    "dhbvn": "Haryana",
    "uhbvn": "Haryana",
    "hpsebl": "Himachal Pradesh",
    "jkpdd_jammu": "Jammu & Kashmir",
    "jkpdd_kashmir": "Jammu & Kashmir",
    "jbvnl": "Jharkhand",
    "bescom": "Karnataka",
    "mescom": "Karnataka",
    "cesc_karnataka": "Karnataka",
    "gescom": "Karnataka",
    "hescom": "Karnataka",
    "kseb": "Kerala",
    "lpdcl": "Ladakh",
    "mppkvvcl": "Madhya Pradesh",
    "mpmkvvcl": "Madhya Pradesh",
    "mpez": "Madhya Pradesh",
    "msedcl": "Maharashtra",
    "adani_mumbai": "Maharashtra",
    "best_mumbai": "Maharashtra",
    "tata_power_mumbai": "Maharashtra",
    "mspdcl": "Manipur",
    "mepdcl": "Meghalaya",
    "ped_mizoram": "Mizoram",
    "doe_nagaland": "Nagaland",
    "tpcodl": "Odisha",
    "tpnodl": "Odisha",
    "tpwodl": "Odisha",
    "tpsodl": "Odisha",
    "pdicl": "Puducherry",
    "pspcl": "Punjab",
    "jvvnl": "Rajasthan",
    "avvnl": "Rajasthan",
    "jdvvnl": "Rajasthan",
    "energy_sikkim": "Sikkim",
    "tangedco": "Tamil Nadu",
    "tsspdcl": "Telangana",
    "tsnpdcl": "Telangana",
    "tsecl": "Tripura",
    "dvvnl": "Uttar Pradesh",
    "mvvnl": "Uttar Pradesh",
    "pvvnl": "Uttar Pradesh",
    "puvvnl": "Uttar Pradesh",
    "kesco": "Uttar Pradesh",
    "upcl": "Uttarakhand",
    "wbsedcl": "West Bengal",
    "cesc_kolkata": "West Bengal",
    "dpl": "West Bengal"
  };
