// js/tariffs/registry.js
// Auto-generated aggregator — imports all per-state files into a single TARIFF_DB.
// Do NOT edit this file directly; update the individual state files instead.

import _andhra_pradesh from './andhra-pradesh.js';
import _arunachal_pradesh from './arunachal-pradesh.js';
import _assam from './assam.js';
import _bihar from './bihar.js';
import _chandigarh from './chandigarh.js';
import _chhattisgarh from './chhattisgarh.js';
import _dadra_and_nagar_haveli_and_daman_and_diu from './dadra-and-nagar-haveli-and-daman-and-diu.js';
import _delhi from './delhi.js';
import _goa from './goa.js';
import _gujarat from './gujarat.js';
import _haryana from './haryana.js';
import _himachal_pradesh from './himachal-pradesh.js';
import _jammu_and_kashmir from './jammu-and-kashmir.js';
import _jharkhand from './jharkhand.js';
import _karnataka from './karnataka.js';
import _kerala from './kerala.js';
import _ladakh from './ladakh.js';
import _madhya_pradesh from './madhya-pradesh.js';
import _maharashtra from './maharashtra.js';
import _manipur from './manipur.js';
import _meghalaya from './meghalaya.js';
import _mizoram from './mizoram.js';
import _nagaland from './nagaland.js';
import _odisha from './odisha.js';
import _puducherry from './puducherry.js';
import _punjab from './punjab.js';
import _rajasthan from './rajasthan.js';
import _sikkim from './sikkim.js';
import _tamil_nadu from './tamil-nadu.js';
import _telangana from './telangana.js';
import _tripura from './tripura.js';
import _uttar_pradesh from './uttar-pradesh.js';
import _uttarakhand from './uttarakhand.js';
import _west_bengal from './west-bengal.js';

export const TARIFF_DB = {};
// Preserves full state modules (incl. state-level metadata like currentRatesFrom)
export const STATE_META = {};
[
  _andhra_pradesh,
  _arunachal_pradesh,
  _assam,
  _bihar,
  _chandigarh,
  _chhattisgarh,
  _dadra_and_nagar_haveli_and_daman_and_diu,
  _delhi,
  _goa,
  _gujarat,
  _haryana,
  _himachal_pradesh,
  _jammu_and_kashmir,
  _jharkhand,
  _karnataka,
  _kerala,
  _ladakh,
  _madhya_pradesh,
  _maharashtra,
  _manipur,
  _meghalaya,
  _mizoram,
  _nagaland,
  _odisha,
  _puducherry,
  _punjab,
  _rajasthan,
  _sikkim,
  _tamil_nadu,
  _telangana,
  _tripura,
  _uttar_pradesh,
  _uttarakhand,
  _west_bengal
].forEach(m => { TARIFF_DB[m.state] = m.discoms; STATE_META[m.state] = m; });

/** @returns {string[]} Sorted list of all state/UT names. */
export function getStates() { return Object.keys(TARIFF_DB).sort(); }

/**
 * Get all DISCOMs in a state.
 * @param {string} state - State name.
 * @returns {Array<{id:string, name:string, fullName:string, area:string}>}
 */
export function getDiscoms(state) { return TARIFF_DB[state] || []; }

/**
 * Find a DISCOM object by its unique id across all states.
 * @param {string} discomId - DISCOM identifier.
 * @returns {Object|null} The DISCOM object, or null.
 */
export function findDiscom(discomId) {
  for (const state of Object.values(TARIFF_DB)) {
    const d = state.find(x => x.id === discomId);
    if (d) return d;
  }
  return null;
}

/** @returns {Array} Categories for the given DISCOM. */
export function getCategories(discomId) {
  const discom = findDiscom(discomId);
  return discom ? discom.categories : [];
}

/** @returns {Object|null} A single category object. */
export function getCategory(discomId, categoryId) {
  const cats = getCategories(discomId);
  return cats.find(c => c.id === categoryId) || null;
}

/** @returns {Array} Supply types within a category (may be empty). */
export function getSupplyTypes(discomId, categoryId) {
  const cat = getCategory(discomId, categoryId);
  return (cat && cat.supplyTypes) ? cat.supplyTypes : [];
}

/**
 * Resolve the effective tariff object for a DISCOM + category + optional supply type.
 * If supply types exist, merges the selected supply type onto the category.
 * @param {string} discomId
 * @param {string} categoryId
 * @param {string} [supplyTypeId]
 * @returns {Object|null}
 */
export function getEffectiveTariff(discomId, categoryId, supplyTypeId) {
  const cat = getCategory(discomId, categoryId);
  if (!cat) return null;
  if (cat.supplyTypes && cat.supplyTypes.length > 0) {
    const st = supplyTypeId
      ? (cat.supplyTypes.find(s => s.id === supplyTypeId) || cat.supplyTypes[0])
      : cat.supplyTypes[0];
    return { ...st, categoryId: cat.id, categoryName: cat.name };
  }
  return { ...cat, categoryId: cat.id, categoryName: cat.name };
}

// ─── Historical (date-versioned) tariff resolution ──────────────────────────────

/**
 * Reverse lookup: find the state metadata object that contains the given DISCOM.
 * @param {string} discomId
 * @returns {Object|null}
 */
export function findStateMetaByDiscom(discomId) {
  for (const [stateName, discoms] of Object.entries(TARIFF_DB)) {
    if (discoms.find(x => x.id === discomId)) return STATE_META[stateName] || null;
  }
  return null;
}

/**
 * Parse an Indian financial year label (e.g. '2025-26') into the FY start date.
 * @param {string} tariffYear - e.g. '2025-26'
 * @returns {string|null} ISO date like '2025-04-01', or null.
 */
export function fyStart(tariffYear) {
  if (!tariffYear) return null;
  const m = String(tariffYear).match(/^(\d{4})/);
  return m ? `${m[1]}-04-01` : null;
}

const DEFAULT_CURRENT_FROM = '2024-04-01';

/**
 * Resolve a tariff to the rate set effective at a given billing date.
 * Supports rateHistory[] for historical billing; falls back to current rates.
 * @param {Object} tariff - Tariff object with optional rateHistory array.
 * @param {string|Date} billingDate - Billing date (ISO string or Date).
 * @param {string} [currentRatesFrom] - When current rates took effect.
 * @param {string} [currentLabel] - Label for the current rate period.
 * @returns {Object} Tariff with periodLabel, estimated flag, and effectiveFrom.
 */
export function resolveDatedTariff(tariff, billingDate, currentRatesFrom, currentLabel) {
  // Spread the whole tariff so non-rate config (demandUnit, excessDemand, excessDemandRate,
  // billingDemandFloorPct, …) carries through to the engine; only the date-versioned RATE fields
  // below are swapped per historical period.
  const currentSet = {
    ...tariff,
    fixedCharge:       tariff.fixedCharge,
    energySlabs:       tariff.energySlabs,
    additionalCharges: tariff.additionalCharges,
    excessDemandRate:  tariff.excessDemandRate,
    fac:               tariff.fac,
  };

  const curFromStr = currentRatesFrom || DEFAULT_CURRENT_FROM;
  // A tariff may self-declare its own period label / estimated flag (e.g. a category refreshed to a
  // newer order ahead of full verification). Those win over the discom-level defaults; when unset,
  // the current set is treated as verified with the discom's FY label, exactly as before.
  const curLabel   = tariff.periodLabel || currentLabel || (tariff.tariffYear ? `FY ${tariff.tariffYear}` : 'Current rates');
  const curEstimated = !!tariff.estimated;

  if (!billingDate) {
    return { ...currentSet, periodLabel: curLabel, estimated: curEstimated, effectiveFrom: curFromStr };
  }
  const bd = billingDate instanceof Date ? billingDate : new Date(billingDate);
  if (isNaN(bd)) {
    return { ...currentSet, periodLabel: curLabel, estimated: curEstimated, effectiveFrom: curFromStr };
  }

  // Build dated candidate list (current + historical overrides)
  const candidates = [{
    from: new Date(curFromStr), label: curLabel, estimated: curEstimated, set: currentSet,
    effectiveFrom: curFromStr
  }];
  for (const h of (tariff.rateHistory || [])) {
    candidates.push({
      from: new Date(h.from),
      label: h.label || h.from,
      estimated: !!h.estimated,
      effectiveFrom: h.from,
      set: {
        ...tariff,
        fixedCharge:       h.fixedCharge       !== undefined ? h.fixedCharge       : tariff.fixedCharge,
        energySlabs:       h.energySlabs       !== undefined ? h.energySlabs       : tariff.energySlabs,
        additionalCharges: h.additionalCharges !== undefined ? h.additionalCharges : tariff.additionalCharges,
        excessDemandRate:  h.excessDemandRate  !== undefined ? h.excessDemandRate  : tariff.excessDemandRate,
        fac:               h.fac               !== undefined ? h.fac               : tariff.fac,
      }
    });
  }
  const dated = candidates.filter(c => !isNaN(c.from)).sort((a, b) => a.from - b.from);

  // Pick the most recent set whose effective date is on/before the billing date
  let chosen = null;
  for (const c of dated) { if (c.from <= bd) chosen = c; }

  if (chosen) {
    return { ...chosen.set, periodLabel: chosen.label, estimated: chosen.estimated,
             effectiveFrom: chosen.effectiveFrom };
  }
  // Billing date predates all known rate sets → carry back earliest, flag as estimated
  const earliest = dated[0];
  return { ...earliest.set, periodLabel: earliest.label, estimated: true,
           carriedBack: true, effectiveFrom: earliest.effectiveFrom };
}
